#!/bin/bash

# Usage:
#  speak <voice_id> <textfile>

 cat $2 | ../piper/piper --cuda --model "../models/nl_BE-nathalie-medium.onnx"  -f "../models/nl_BE-nathalie-medium.onnx.json" --output-raw | aplay -q -r 22050 -f S16_LE -t raw -
